example_blocks = [
    [
        {"token": "CONCLUSION", "label": "O", "idx": 0},
        {"token": "\n", "label": "O", "idx": 1},
    ],
    [
        {"token": "The", "label": "C", "idx": 2},
        {"token": "applicant", "label": "C", "idx": 3},
        {"token": "complained", "label": "C", "idx": 4},
        {"token": "of", "label": "C", "idx": 5},
        {"token": "the", "label": "C", "idx": 6},
        {"token": "inadequate", "label": "C", "idx": 7},
        {"token": "conditions", "label": "C", "idx": 8},
        {"token": "of", "label": "C", "idx": 9},
        {"token": "his", "label": "C", "idx": 10},
        {"token": "detention", "label": "C", "idx": 11},
        {"token": "and", "label": "C", "idx": 12},
        {"token": "that", "label": "C", "idx": 13},
        {"token": "he", "label": "C", "idx": 14},
        {"token": "had", "label": "C", "idx": 15},
        {"token": "no", "label": "C", "idx": 16},
        {"token": "effective", "label": "C", "idx": 17},
        {"token": "remedy", "label": "C", "idx": 18},
        {"token": "in", "label": "C", "idx": 19},
        {"token": "this", "label": "C", "idx": 20},
        {"token": "connection", "label": "C", "idx": 21},
    ],
    [
        {"token": ".", "label": "O", "idx": 22},
        {"token": "He", "label": "O", "idx": 23},
        {"token": "relied", "label": "O", "idx": 24},
        {"token": "on", "label": "O", "idx": 25},
        {"token": "Articles", "label": "O", "idx": 26},
        {"token": "3", "label": "O", "idx": 27},
        {"token": "and", "label": "O", "idx": 28},
        {"token": "13", "label": "O", "idx": 29},
        {"token": "of", "label": "O", "idx": 30},
        {"token": "the", "label": "O", "idx": 31},
        {"token": "Convention", "label": "O", "idx": 32},
        {"token": ",", "label": "O", "idx": 33},
        {"token": "which", "label": "O", "idx": 34},
        {"token": "read", "label": "O", "idx": 35},
        {"token": "as", "label": "O", "idx": 36},
        {"token": "follows", "label": "O", "idx": 37},
        {"token": ":", "label": "O", "idx": 38},
        {"token": "\n", "label": "O", "idx": 39},
        {"token": "Article", "label": "O", "idx": 40},
        {"token": "3", "label": "O", "idx": 41},
        {"token": "\n", "label": "O", "idx": 42},
    ],
    [
        {"token": "No", "label": "P", "idx": 43},
        {"token": "one", "label": "P", "idx": 44},
        {"token": "shall", "label": "P", "idx": 45},
        {"token": "be", "label": "P", "idx": 46},
        {"token": "subjected", "label": "P", "idx": 47},
        {"token": "to", "label": "P", "idx": 48},
        {"token": "torture", "label": "P", "idx": 49},
        {"token": "or", "label": "P", "idx": 50},
        {"token": "to", "label": "P", "idx": 51},
        {"token": "inhuman", "label": "P", "idx": 52},
        {"token": "or", "label": "P", "idx": 53},
        {"token": "degrading", "label": "P", "idx": 54},
        {"token": "treatment", "label": "P", "idx": 55},
        {"token": "or", "label": "P", "idx": 56},
        {"token": "punishment", "label": "P", "idx": 57},
    ],
    [
        {"token": "\n", "label": "O", "idx": 58},
        {"token": "Article", "label": "O", "idx": 59},
        {"token": "13", "label": "O", "idx": 60},
        {"token": "\n", "label": "O", "idx": 61},
    ],
    [
        {"token": "Everyone", "label": "P", "idx": 62},
        {"token": "whose", "label": "P", "idx": 63},
        {"token": "rights", "label": "P", "idx": 64},
        {"token": "and", "label": "P", "idx": 65},
        {"token": "freedoms", "label": "P", "idx": 66},
        {"token": "as", "label": "P", "idx": 67},
        {"token": "set", "label": "P", "idx": 68},
        {"token": "forth", "label": "P", "idx": 69},
        {"token": "in", "label": "P", "idx": 70},
        {"token": "this", "label": "P", "idx": 71},
        {"token": "Convention", "label": "P", "idx": 72},
        {"token": "are", "label": "P", "idx": 73},
        {"token": "violated", "label": "P", "idx": 74},
        {"token": "shall", "label": "P", "idx": 75},
        {"token": "have", "label": "P", "idx": 76},
        {"token": "punishment", "label": "P", "idx": 77},
        {"token": "an", "label": "P", "idx": 78},
        {"token": "effective", "label": "P", "idx": 79},
        {"token": "remedy", "label": "P", "idx": 80},
        {"token": "before", "label": "P", "idx": 81},
        {"token": "a", "label": "P", "idx": 82},
        {"token": "national", "label": "P", "idx": 83},
        {"token": "authority", "label": "P", "idx": 84},
    ],
    [
        {"token": ".", "label": "O", "idx": 85},
        {"token": ".", "label": "O", "idx": 86},
        {"token": ".", "label": "O", "idx": 87},
    ]
]

example_claims = [
    [
        {"token": "The", "label": "C", "idx": 2},
        {"token": "applicant", "label": "C", "idx": 3},
        {"token": "complained", "label": "C", "idx": 4},
        {"token": "of", "label": "C", "idx": 5},
        {"token": "the", "label": "C", "idx": 6},
        {"token": "inadequate", "label": "C", "idx": 7},
        {"token": "conditions", "label": "C", "idx": 8},
        {"token": "of", "label": "C", "idx": 9},
        {"token": "his", "label": "C", "idx": 10},
        {"token": "detention", "label": "C", "idx": 11},
        {"token": "and", "label": "C", "idx": 12},
        {"token": "that", "label": "C", "idx": 13},
        {"token": "he", "label": "C", "idx": 14},
        {"token": "had", "label": "C", "idx": 15},
        {"token": "no", "label": "C", "idx": 16},
        {"token": "effective", "label": "C", "idx": 17},
        {"token": "remedy", "label": "C", "idx": 18},
        {"token": "in", "label": "C", "idx": 19},
        {"token": "this", "label": "C", "idx": 20},
        {"token": "connection", "label": "C", "idx": 21},
    ],
]

example_premises = [
    [
        {"token": "No", "label": "P", "idx": 43},
        {"token": "one", "label": "P", "idx": 44},
        {"token": "shall", "label": "P", "idx": 45},
        {"token": "be", "label": "P", "idx": 46},
        {"token": "subjected", "label": "P", "idx": 47},
        {"token": "to", "label": "P", "idx": 48},
        {"token": "torture", "label": "P", "idx": 49},
        {"token": "or", "label": "P", "idx": 50},
        {"token": "to", "label": "P", "idx": 51},
        {"token": "inhuman", "label": "P", "idx": 52},
        {"token": "or", "label": "P", "idx": 53},
        {"token": "degrading", "label": "P", "idx": 54},
        {"token": "treatment", "label": "P", "idx": 55},
        {"token": "or", "label": "P", "idx": 56},
        {"token": "punishment", "label": "P", "idx": 57},
    ],
    [
        {"token": "Everyone", "label": "P", "idx": 62},
        {"token": "whose", "label": "P", "idx": 63},
        {"token": "rights", "label": "P", "idx": 64},
        {"token": "and", "label": "P", "idx": 65},
        {"token": "freedoms", "label": "P", "idx": 66},
        {"token": "as", "label": "P", "idx": 67},
        {"token": "set", "label": "P", "idx": 68},
        {"token": "forth", "label": "P", "idx": 69},
        {"token": "in", "label": "P", "idx": 70},
        {"token": "this", "label": "P", "idx": 71},
        {"token": "Convention", "label": "P", "idx": 72},
        {"token": "are", "label": "P", "idx": 73},
        {"token": "violated", "label": "P", "idx": 74},
        {"token": "shall", "label": "P", "idx": 75},
        {"token": "have", "label": "P", "idx": 76},
        {"token": "punishment", "label": "P", "idx": 77},
        {"token": "an", "label": "P", "idx": 78},
        {"token": "effective", "label": "P", "idx": 79},
        {"token": "remedy", "label": "P", "idx": 80},
        {"token": "before", "label": "P", "idx": 81},
        {"token": "a", "label": "P", "idx": 82},
        {"token": "national", "label": "P", "idx": 83},
        {"token": "authority", "label": "P", "idx": 84},
    ],
]
